[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.28"
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[fuzz]
runs = 10000
max_test_rejects = 65536

[invariant]
runs = 256
depth = 64

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
